/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
    Drupal.color = {
      logoChanged: false,
      bgChanged: false,
      callback: function callback(context, settings, $form) {
        var $colorPreview = $form.find('.color-preview');
        var $colorPalette = $form.find('.js-color-palette');

        $colorPreview.css({'--background': $colorPalette.find('input[name="palette[primary]"]').val()});
      }
    };
  })(jQuery, Drupal, drupalSettings);

