<?php

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_alias_help($route_name, RouteMatchInterface $route_match)
{
    if ($route_name === 'help.page.node_alias') {
        $output = '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('Make custom alias on node.') . '</p>';
        $output .= '<h3>' . t('Uses') . '</h3>';
        $output .= '<p>' . t('// TODO') . '</p>';

        return $output;
    }
}
