<?php

declare(strict_types=1);

function request_validation_help(string $route_name): ?string
{
    $output = null;

    switch ($route_name) {
        case 'help.page.request_validation':
            $text = file_get_contents(dirname(__FILE__) . "/README.md");
            if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
                $output = '<pre>' . $text . '</pre>';
            } else {
                $filter_manager = \Drupal::service('plugin.manager.filter');
                $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
                $config = ['settings' => $settings];
                $filter = $filter_manager->createInstance('markdown', $config);
                //@phpstan-ignore-next-line
                $output = $filter->process($text, 'en');
            }
    }

    return $output;
}
