
@baseUrl = http://drupal10.localhost

# @name getPostNodeListWithDrupalNode
GET {{baseUrl}}/api/rest/posts?_format=json  HTTP/1.1

###

# @name getPage2PostNodeListWithDrupalNode
@limit = 5
@page = 2
GET {{baseUrl}}/api/rest/posts?_format=json&page={{page}}&limit={{limit}}  HTTP/1.1

###

# @name getPostNodeWithDrupalNode
GET {{baseUrl}}/api/rest/posts/101?_format=json  HTTP/1.1
Content-Type: application/json

###

# @name getNotFoundPostNodeWithDrupalNode
GET {{baseUrl}}/api/rest/posts/999999?_format=json HTTP/1.1
Content-Type: application/json
