name: Test Drupal module

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'sandbox/snippets/tests/**'

env:
  REGISTRY: ghcr.io
  REPOSITORY: spooky063/standalone-drupal
  TAG: 1.0.0-php8.4-drupal11.x-dev

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.TAG }}

      - name: Execute tests
        run: |
          docker run --rm \
          -e SIMPLETEST_DB=sqlite://localhost/sites/default/files/.test.sqlite \
          -e SIMPLETEST_BASE_URL=http://localhost \
          -v ./sandbox/snippets/tests/phpunit.xml.dist:/srv/app/phpunit.xml.dist:ro \
          -v ./sandbox/snippets/tests:/srv/app/web/modules/custom:ro \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.TAG }} \
          phpunit --testdox --testsuite unit,kernel --coverage-text
