name: Test Drupal module

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - sandbox/snippets/tests/**

env:
  REGISTRY: ghcr.io
  REPOSITORY: spooky063/standalone-drupal
  TAG: 1.0.0-php8.4-drupal11.x-dev

jobs:
  test:
    name: Test Drupal custom module
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.TAG }}

      - name: Execute tests with code coverage
        run: |
          docker run --rm \
          -e SIMPLETEST_DB=sqlite://localhost/sites/default/files/.test.sqlite \
          -e SIMPLETEST_BASE_URL=http://localhost \
          -e XDEBUG_MODE=coverage \
          -v ${{ github.workspace }}/sandbox/snippets/tests/phpunit.xml.dist:/srv/app/phpunit.xml.dist \
          -v ${{ github.workspace }}/sandbox/snippets/tests:/srv/app/web/modules/custom \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.TAG }} \
          phpunit --testdox --testsuite unit,kernel --coverage-text --log-junit junit.xml --coverage-clover=coverage.xml

      - name: Upload test results to Codecov.io
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload code coverage data to Codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
