name: Test Drupal module

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - sandbox/snippets/tests/**

env:
  REGISTRY: ghcr.io
  REPOSITORY: spooky063/standalone-drupal
  TAG: 1.0.0-php8.4-drupal11.x-dev

jobs:
  test:
    name: Test Drupal custom module
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/spooky063/standalone-drupal:1.0.0-php8.4-drupal11.x-dev
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        SIMPLETEST_DB: sqlite://localhost/sites/default/files/.test.sqlite
        SIMPLETEST_BASE_URL: http://localhost
        XDEBUG_MODE: coverage
      ports:
        - 80
      volumes:
        - /sandbox/snippets/tests/phpunit.xml.dist:/srv/app/phpunit.xml.dist
        - /sandbox/snippets/tests:/srv/app/web/modules/custom

    steps:
      - name: Check if modules exists
        run: ls -lah /srv/app/web/modules/custom

      - name: Execute tests
        run: phpunit --testdox --testsuite unit,kernel --coverage-text
